apiVersion: v1
kind: Service
metadata:
  name: nacos
  labels:
    app: nacos
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
    - port: 8848
      name: server
      targetPort: 8848
  clusterIP: None
  selector:
    app: nacos
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nacos
spec:
  rules:
    - host: TMP_NACOS_HOST_NAME
      http:
        paths:
          - backend:
              serviceName: nacos
              servicePort: 8848