- name: 清理已安装的docker
  shell: "{{ item }}"
  with_items:
    - rm -rf /etc/docker/;
    - yum clean all;
    - yum remove docker* -y;

- name: 清理已安装的kubelet
  shell: "{{ item }}"
  with_items:
    - echo y | kubeadm reset;
    - rm -rf ~/.kube/;
    - rm -rf /etc/kubernetes/;
    - rm -rf /etc/systemd/system/kubelet.service.d;
    - rm -rf /etc/systemd/system/kubelet.service;
    - rm -rf /usr/bin/kube*;
    - rm -rf /etc/cni;
    - rm -rf /opt/cni;
    - rm -rf /var/lib/etcd;
    - rm -rf /var/etcd;
    - yum clean all;
    - yum remove kube* -y;
  ignore_errors: yes