
- hosts: nfs-master
  vars_files: ../configs/component_config.yml
  roles:
    - ../roles/component_nfs_master
- hosts: nfs-node
  vars_files: ../configs/component_config.yml
  roles:
    - ../roles/component_nfs_node
    
