apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm
data:
  nginx_conf: |-
    #user  nobody;
    worker_processes  1;
    events {
        worker_connections  1024;
    }
    http {
        include       mime.types;
        default_type  application/octet-stream;
        sendfile        on;
        keepalive_timeout  65;
        server {
                listen       80;
                server_name  TMP_NGINX_LISTEN_HOST;
                charset utf-8;
                index index.html index.htm index.jsp;
                location ~ {
                     root /usr/share/nginx/html;
                }
        }
    }