- name: 清理yum进程
  shell: '{{ item }}'
  with_items:
    - rm -rf /var/run/yum.pid

- name: 安装 nfs
  yum:
    name:
      - nfs-utils
      - rpcbind
    state: latest

- name: 创建共享目录
  file: path=/data state=directory

- name: 配置共享目录
  shell: '{{ item }}'
  with_items:
    - mkdir -p /data
    - chmod 777 -R /data
    - echo "/data *(rw,sync,no_root_squash)" > /etc/exports


- name: 启动nfs服务
  service: name='{{ item }}' state=started enabled=true
  with_items:
    - rpcbind
    - nfs

- name: 拷贝nfs服务
  copy: src=./files/ dest=/tmp/nfs-configs/

- name: 配置设置服务器ip
  shell: "sed -i \"s/NFS_SERVER_HOST/{{ nfs.server }}/g\" /tmp/nfs-configs/deloyment.yaml"

- name: 部署nfs服务
  shell: '{{ item }}'
  with_items:
    - kubectl apply -f /tmp/nfs-configs/
