---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '3'
  labels:
    app: xxl-job
    k8s.kuboard.cn/layer: cloud
  name: xxl-job
  namespace: default
spec:
  minReadySeconds: 60
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: xxl-job
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: xxl-job
        tier: xxl-job
    spec:
      containers:
        - env:
            - name: TZ
              value: Asia/Shanghai
            - name: PARAMS
              value: >-
                --spring.datasource.url=jdbc:mysql://TMP_XXL_JOB_MYSQL_HOST:TMP_XXL_JOB_MYSQL_PORT/TMP_XXL_JOB_MYSQL_DB_NAME?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
                --spring.datasource.username=TMP_XXL_JOB_MYSQL_USER
                --spring.datasource.password=TMP_XXL_JOB_MYSQL_PASSWORD
                --server.context-path=/job
          image: 'xuxueli/xxl-job-admin:2.2.0'
          imagePullPolicy: Always
          name: xxl-job
          ports:
            - containerPort: 8080
              name: java
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xxl-job
  name: xxl-job
  namespace: default
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: xxl-job
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: xxl-job
  namespace: default
spec:
  rules:
    - host: TMP_XXL_JOB_HOST_NAME
      http:
        paths:
          - backend:
              serviceName: xxl-job
              servicePort: 8080
            path: /

